name: paypay_sample
description: "This Project is a sample of PayPay integration with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PayPay
  paypay_uo: ^0.1.3

  # State Management
  flutter_riverpod: ^2.4.9

  # Routing
  go_router: ^13.2.0

  # Annotation
  freezed_annotation: ^2.4.1
  flutterfire_gen_annotation: ^0.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4

  # Firebase
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_dynamic_links: ^5.4.12
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6

  # UI
  url_launcher: ^6.0.20
  image_picker: ^1.0.7
  gap: ^3.0.1

  # Utility
  flutterfire_gen_utils: ^0.4.1
  logger: ^1.4.0
  flutter_gen: ^5.4.0
  dotenv: ^4.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  json_serializable:
  flutterfire_gen:
  pedantic_mono:
  riverpod_generator:
  flutter_gen_runner:

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/config
